version: '3'

services:
  backend:
    container_name: backend
    image: node:18-alpine
    ports:
      - 3000:3000
    env_file:
      - .env
    depends_on:
      - db
    stdin_open: true
    tty: true
    working_dir: /application
    volumes:
      - ./:/application
  db:
    container_name: banco_de_dados
    image: mysql:8.0
    ports:
      - 3306:3306
    env_file:
      - .env
    volumes:
      - ./data:/var/lib/mysql
      - ./dumps:/docker-entrypoint-initdb.d/